Add warning for tune == nattune
pylhc/Beta-Beat.src pull request #210
Opened 2020-10-02 13:54 UTC by Mael-Le-Garrec

Fixes #209

2020-10-02 14:01 UTC, Mael-Le-Garrec commented
Not sure if that's the right place to put the warning or not

2020-10-05 09:39 UTC, JoschD commented
> Not sure if that's the right place to put the warning or not


Good question. 

I thought we would already check the input, if the tune-windows have no overlap? @lmalina ?
If we want this check, I would put it a bit further into harpy, though. So that harpy itself throws this warning.

2020-10-05 10:04 UTC, lmalina commented
> > Not sure if that's the right place to put the warning or not
> 
> Good question.
> 
> I thought we would already check the input, if the tune-windows have no overlap? @lmalina ?
> If we want this check, I would put it a bit further into harpy, though. So that harpy itself throws this warning.
> (easier for debugging, if you want to find out with what files/settings this message is thrown)

@JoschD  is right, we should already check the input. I would not put it straight into (old) Harpy though. The proper place is in the input handler, where the HarpyInput is initialised:

https://github.com/pylhc/Beta-Beat.src/blob/30350b99126be40451e9bb71639bd63c0c6c9525/harmonic_analysis/io_handlers/input_handler.py#L290

2020-10-05 10:08 UTC, Mael-Le-Garrec commented
> @JoschD is right, we should already check the input. I would not put it straight into (old) Harpy though. The proper place is in the input handler, where the HarpyInput is initialised:
> 
> https://github.com/pylhc/Beta-Beat.src/blob/30350b99126be40451e9bb71639bd63c0c6c9525/harmonic_analysis/io_handlers/input_handler.py#L290

My warning is being thrown after having run Harpy, not before. How would you do it there?

2020-10-05 10:15 UTC, lmalina commented
> > @JoschD is right, we should already check the input. I would not put it straight into (old) Harpy though. The proper place is in the input handler, where the HarpyInput is initialised:
> > https://github.com/pylhc/Beta-Beat.src/blob/30350b99126be40451e9bb71639bd63c0c6c9525/harmonic_analysis/io_handlers/input_handler.py#L290
> 
> My warning is being thrown after having run Harpy, not before. How would you do it there?

As I suggested earlier and later discussed also in the OMC meeting, check something like `abs(tune - nattune)> 2 * tolerance`, warn otherwise.

2020-10-05 10:17 UTC, Mael-Le-Garrec commented
> > My warning is being thrown after having run Harpy, not before. How would you do it there?
> 
> As I suggested earlier and later discussed also in the OMC meeting, check something like `abs(tune - nattune)> 2 * tolerance`, warn otherwise.

That still needs to be done after, or am I mistaken?

2020-10-05 10:22 UTC, lmalina commented
> > > My warning is being thrown after having run Harpy, not before. How would you do it there?
> > 
> > 
> > As I suggested earlier and later discussed also in the OMC meeting, check something like `abs(tune - nattune)> 2 * tolerance`, warn otherwise.
> 
> That still needs to be done after, or am I mistaken?

You need to check the options. The tunes, etc... are later found within interval, e.g. `(tune-tolerance, tune+tolerance)`.

2020-10-05 14:49 UTC, JoschD requested changes

2020-10-05 14:49 UTC, JoschD commented on harmonic_analysis/io_handlers/input_handler.py
> +                msg = ("Natural tune will not be found for plane {} with such"
More explicit:
"Windows for tune and natural tune in plane {} overlap for tolerance {}. This could lead to both tunes being found at the same frequency"

2020-10-05 14:52 UTC, JoschD commented
Question: 
The warning before does not tell the user if the tunes are actually equal when found. Should that then throw an error? Or another warning? ("I told you so")

if so I would put it into harpy at the end.

2020-10-05 14:54 UTC, Mael-Le-Garrec commented
> Question:
> The warning before does not tell the user if the tunes are actually equal when found. Should that then throw an error? Or another warning? ("I told you so")
> 
> if so I would put it into harpy at the end.

Yeah, that's why my initial warning was placed after having run harpy and not before.
Do we want both? Are there cases where you don't care if the nattune if found or not?

2020-10-06 13:28 UTC, JoschD approved these changes
I like it

2020-10-06 13:32 UTC, awegsche commented
nitpicking: in the comment it still says `throw warning`

I still think that a simple warning should be enough. What if we actually kicked on the tune?

2020-10-06 14:16 UTC, merged