add knob_extraction and python3 property
pylhc/Beta-Beat.src pull request #232
Opened 2022-04-29 14:58 UTC by awegsche

this adds the python side of knob extraction.

it's a python3 module (using pytimber), so calling this is a hacky business. please refer to the [corresponding merge request in the GUI](https://gitlab.cern.ch/acc-co/lhc/lhc-app-beta-beating/-/merge_requests/33)

2022-04-29 16:29 UTC, fsoubelet requested changes
I do not like this in its current state. Few more comments on top of the review ones:
- All printing should be proper logging.
- I don't like that we're mixing python3 scripts in here. 


In my opinion, this should be a clean script in `PyLHC` which would be called even easier from the GUI. It would also enable us to use some of the goodies from the rest of our Python ecosystem, like the mock imports, the AccDateTime utilities and such.

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +    parser.add_argument("knobs", type=str, nargs='*',
I would rather have a `store_true` flag for each of them, so one would just then:
```bash
python Beta-Beat.src/mode/knob_extractor.py --disp --xing
```

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +    parser.add_argument("--extract", type=str, nargs='+',
This should really be a `--time` flag

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +    parser.add_argument("--subscribe", action='store_true',
How much added value is there in this? I would rather leave it out for now (cf next comment).

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +main()
Needs an `if __name__ == "main"` block so things could also be imported if needed.

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +        except:  # I am going to use bare except whenever I want
Really? You need to write this?

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +import argparse
Am I correct that this can only be ran from the technical network, since it needs to access NXCALS?
If so, we should probably put a module docstring to specify that.

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +            outfile.write("!! --- {:12} ---\n".format(knob))
f-strings please since this is Python 3

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +                        help=("this flag activates an interactive subscription mode."
Incorrect help string

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +    return None
Does this handle the UTC <--> accelerator time?

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +        print("!! Subscription not yet implemented")
Let's not advertise options that don't really exist.

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +    return t1
This is **VERY** hacky. I would *really* rather us use a good datetime library to handle this rather than doing an in-house hack.

2022-04-29 16:29 UTC, fsoubelet commented on model/knob_extractor.py
> +def _get_knobs_dict(user_defined = None):
We should clarify here that this expects a Path/File-like value for `user_defined`. Also, please `pathlib`.

2022-05-02 07:43 UTC, awegsche commented on model/knob_extractor.py
> +    parser.add_argument("knobs", type=str, nargs='*',
no
I find the positional arg one much more functional

2022-05-02 07:44 UTC, awegsche commented on model/knob_extractor.py
> +    parser.add_argument("--extract", type=str, nargs='+',
I disagree also on that point. This flag is to extract the knobs at the given time, so the flag should be `extract`

2022-05-02 07:44 UTC, awegsche commented on model/knob_extractor.py
> +main()
but it is not needed

2022-05-02 07:45 UTC, awegsche commented on model/knob_extractor.py
> +        except:  # I am going to use bare except whenever I want
I actually don't, this can be removed. I just got annoyed by the IDE flagging this line wit a warning

2022-05-02 07:47 UTC, awegsche commented on model/knob_extractor.py
> +    return t1
it's not hacky. maybe unnecessary, since (for now) we only want to extract a single value (so we could actually get rid of the t2, altogether)

2022-05-20 09:58 UTC, awegsche commented on model/knob_extractor.py
> +    parser.add_argument("--subscribe", action='store_true',
removed

2022-05-20 09:59 UTC, awegsche commented on model/knob_extractor.py
> +main()
added, although I really don't think it's needed

2022-05-20 10:00 UTC, awegsche commented on model/knob_extractor.py
> +    return None
that's not an issue, it's all handled by the standard library

2022-05-20 10:01 UTC, awegsche commented on model/knob_extractor.py
> +    return t1
I'm already using the standard library for the actual handling of data and time

2022-06-03 17:03 UTC, JoschD requested changes

2022-06-03 17:03 UTC, JoschD commented on model/knob_extractor.py
> +    # if all fails, fall back to lhc acc-models
A docstring what this function does and why we need a knobdict in the firstplace would go along way in understanding what you are doing

2022-06-03 17:03 UTC, JoschD commented on model/knob_extractor.py
> +                (madxname, scaling) = knobdict[knobname.replace(":", "/")]
I still don't know what the knobdict is doing. It's a mapping from LSA names to madx names and scaling?  where scaling is the knob-value? Shouldn't this default to the lsa-to-madx conversion with a scaling of 1?

2022-06-03 17:35 UTC, JoschD commented on model/knob_extractor.py
> +    parser.add_argument("knobs", type=str, nargs='*',
please rename to `--extract` because it's the knobs to **extract** /s

2022-06-03 17:36 UTC, JoschD commented on model/knob_extractor.py
> +    parser.add_argument("--state", action='store_true',
please rename to `--extract` because  it's **extracts** the state. /s

2022-06-03 17:38 UTC, JoschD commented on model/knob_extractor.py
> +    parser.add_argument("--output", type=str, default='knobs.madx',
please rename to `--extract` as it **extract** to the output file. /s

2022-06-04 11:57 UTC, fsoubelet commented on model/model_creators/lhc_model_creator.py
> +readmytable, file = "/afs/cern.ch/eng/sl/lintrack/error_tables/Beam{}/{}.errors", table=errtab;
Also, this tries to read an inexistant file for B2 at 6.8TeV

2022-06-04 12:46 UTC, awegsche commented on model/model_creators/lhc_model_creator.py
> +readmytable, file = "/afs/cern.ch/eng/sl/lintrack/error_tables/Beam{}/{}.errors", table=errtab;
are you sure that it's in this line?

2022-06-04 12:56 UTC, awegsche commented on model/model_creators/lhc_model_creator.py
> +readmytable, file = "/afs/cern.ch/eng/sl/lintrack/error_tables/Beam{}/{}.errors", table=errtab;
so, this is probably caused by the madx template using the `ENERGY` flag to determine the error tables name.
this leads to loading the error tables _twice_ for the energies up to 6.8TeV (and including 6.8TeV for beam 1).
But for backwards compatibility this cannot be removed. 

**Applied fix:** override the corresponding macro in `madx/lib/runIII_2022.madx` to ab empty one.

2022-06-04 13:21 UTC, awegsche commented on model/knob_extractor.py
> +                (madxname, scaling) = knobdict[knobname.replace(":", "/")]
done

2022-06-04 13:21 UTC, awegsche commented on model/knob_extractor.py
> +    # if all fails, fall back to lhc acc-models
done

2022-06-04 13:26 UTC, awegsche commented on model/knob_extractor.py
> +    parser.add_argument("--output", type=str, default='knobs.madx',
I am not going to change the interface. those jokes won't change my mind ...

2022-06-04 13:26 UTC, awegsche commented on model/knob_extractor.py
> +def _get_knobs_dict(user_defined = None):
done

2022-06-04 13:26 UTC, awegsche commented on model/knob_extractor.py
> +    parser.add_argument("--extract", type=str, nargs='+',
no

2022-06-04 13:27 UTC, awegsche commented on model/knob_extractor.py
> +    print(f"couldn't read datetime '{pattern}'")
catching the `None` now

2022-09-22 13:56 UTC, awegsche commented
Close to reopen

2022-09-22 13:56 UTC, closed without merging